### PR TITLE
gracefully handle greeting toggle

### LINKED ISSUE #32: panics when providing `-g` option
* version: 0.4.1
* installed via cargo

```
$ wthrr -g
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/xxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/wthrr-0.4.1/src/modules/params/greeting.rs:9:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by arctic-penguin**
fixes #32

### CODE REVIEW

**Comment by tobealive** [comment]
Thanks for the PR @arctic-penguin 

Please let me know if you'd like to implement the requested changes. I could also push them and then merge your PR if that's of any help!

**Comment by arctic-penguin** [comment]
@tobealive I'm not sure what you mean. All the required changes are in my PR, and could be merged as-is. Am I missing something?

File: src/modules/params/greeting.rs [hunk 1]
```diff
@@ -1,17 +1,18 @@
...
+		Ok(greet)
+	} else {
+		Ok(!args_toggle_greeting)
 	}
+}
 
-	let greet = match args_toggle_greeting {
-		true => !config_greet.unwrap(),
-		_ => config_greet.unwrap(),
-	};
```
Comment (tobealive) [inline src/modules/params/greeting.rs:11]: The preferred approach would be to extend the `unwrap()` function to fall back on the configuration defaults. 

This would be more uniform with the way such edge cases are handled in the rest of the application. It will also be a bit leaner, since we use the guard clause to exist early, and cleaner to read, since we can maintain a relatively low level of nesting without wrapping the entire function contents in a conditional statement.

```rs
let greet = match args_toggle_greeting {
	true => !config_greet.unwrap_or_else(|| Config::default().greeting.unwrap()),
	_ => config_greet.unwrap_or_else(|| Config::default().greeting.unwrap()),
};
```

the Config module probably needs to be imported.

File: src/modules/params/greeting.rs [hunk 2]
```diff
@@ -1,17 +1,18 @@
 use anyhow::Result;
 
 pub fn get(args_toggle_greeting: bool, config_greet: Option<bool>) -> Result<bool> {
-	if !args_toggle_greeting && config_greet.is_none() {
-		return Ok(true);
```
Comment (tobealive) [inline src/modules/params/greeting.rs:5]: In fact with the requested changes below we wouldn't even need the guard clause anymore. This would slim it down further. So no need to revert this removal.

**Review by tobealive — CHANGES_REQUESTED** [review]

**Comment by tobealive** [comment]
> @tobealive I'm not sure what you mean. All the required changes are in my PR, and could be merged as-is. Am I missing something?

I think the review got stuck. It should be visible now.

File: src/modules/params/greeting.rs (hunk 1 above)
Comment (arctic-penguin) [reply src/modules/params/greeting.rs]: done

**Comment by tobealive** [comment]
Looks good. Thank you!

**Review by tobealive — APPROVED** [review]
